name: Romm
version: 1.1.0
slug: romm
description: |
  A beautiful, powerful, self-hosted ROM manager and player.
  Scan, enrich, browse and play your game collection with metadata from
  IGDB, Screenscraper, and MobyGames. Features custom artwork from SteamGridDB,
  RetroAchievements display, in-browser gameplay via EmulatorJS and RuffleRS,
  support for 400+ platforms, multi-disk games, DLCs, mods, hacks, patches,
  manuals, and sharing with friends.
arch:
  - aarch64
  - amd64
image: ghcr.io/rigerc/ha-apps-romm-{arch}
startup: system
boot: manual
url: https://github.com/rigerc/ha-apps
init: false
ports:
  5999/tcp: 5999
ports_description:
  5999/tcp: ROMM web interface
webui: http://[HOST]:[PORT:5999]
map:
  - share:rw
  - addon_config:rw
options:
  log_level: info
  database:
    host: core-mariadb
    port: 3306
    name: romm
    user: romm-user
    password: ''
  auth_secret_key: ''
  metadata_providers:
    screenscraper_user: ''
    screenscraper_password: ''
    retroachievements_api_key: ''
    steamgriddb_api_key: ''
    igdb_client_id: ''
    igdb_client_secret: ''
    mobygames_api_key: ''
    hasheous_enabled: true
    playmatch_enabled: true
    launchbox_enabled: true
  library_path: /share/roms
  env_vars: []
  scheduled_tasks:
    enable_rescan: true
    enable_switch_titledb: true
    enable_launchbox_metadata: true
    enable_image_conversion: true
    enable_retroachievements_sync: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  database:
    host: str
    port: int(1,65535)
    name: str
    user: str
    password: password
  auth_secret_key: str
  metadata_providers:
    screenscraper_user: str?
    screenscraper_password: password?
    retroachievements_api_key: password?
    steamgriddb_api_key: password?
    igdb_client_id: str?
    igdb_client_secret: password?
    mobygames_api_key: password?
    hasheous_enabled: bool
    playmatch_enabled: bool
    launchbox_enabled: bool
  library_path: str
  env_vars:
    - str?
  scheduled_tasks:
    enable_rescan: bool
    enable_switch_titledb: bool
    enable_launchbox_metadata: bool
    enable_image_conversion: bool
    enable_retroachievements_sync: bool
