name: Kapowarr
version: 1.1.3
slug: kapowarr
description: |
  Comic book library manager. Build and manage a digital library of comics
  with automated downloading, renaming, and conversion. Supports downloading
  directly or via services like MediaFire and Mega. Get metadata from
  Comic Vine and manage your collection with the recognizable *arr UI.
url: https://github.com/rigerc/ha-apps
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: manual
ingress: true
ingress_port: 9919
panel_icon: mdi:book-open-page-variant
map:
  - share:rw
  - addon_config:rw
options:
  log_level: info
  timezone: UTC
schema:
  log_level: list(trace|debug|info|warning|error)
  timezone: str
#image: ghcr.io/rigerc/ha-apps-kapowarr-{arch}
