name: Kapowarr
version: 1.3.0
slug: kapowarr
description: >-
  Comic book library manager with automated downloading, renaming, and
  conversion.
url: https://github.com/Casvt/Kapowarr
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: manual
ingress: true
ingress_port: 9919
panel_icon: mdi:book-open-page-variant
map:
  - addon_config:rw
  - share:rw
options:
  log_level: info
  timezone: UTC
schema:
  log_level: list(trace|debug|info|warning|error)
  timezone: str
