name: Profilarr
version: 1.1.0
slug: profilarr
description: |
  Import, export, sync and delete quality profiles and custom formats
  via Radarr and Sonarr API. Centrally manage your *arr configurations,
  sync master instances with multiple servers, and backup/restore profiles
  with Git-backed configuration storage.
url: https://github.com/rigerc/ha-apps
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: manual
ingress: true
ingress_port: 8019
panel_icon: mdi:cog-transfer
map:
  - share:rw
  - addon_config:rw
options:
  auth_mode: 'on'
  log_level: info
  git_user_name: Profilarr
  git_user_email: profilarr@homeassistant.local
schema:
  auth_mode: list(on|local|oidc|off)
  log_level: list(trace|debug|info|warning|error)
  git_user_name: str?
  git_user_email: str?
image: ghcr.io/rigerc/ha-apps-profilarr-{arch}
